# YAML EXPLANATION FILE #

Name: Mr.Holmes
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++
Python-Version: Python3 
Author: Luca Garofalo (Lucksi)
Copyright: (C) 2021-2022 Lucksi
Project-site: https://lucksi.github.io/Mr.Holmes
Download: git clone https://github.com/Lucksi/Mr.Holmes
Platforms: Linux/MacOS/Termux/Windows
Version: Nuke1.0.1(V6)
License: GNU General Public License v3.0
